#!/bin/sh
[ -n "$CI" ] && exit 0

# source 'husky.sh'
. "$(dirname "$0")/_/husky.sh"


. "$(dirname "$0")/build_image"
. "$(dirname "$0")/test_build"

main () {
    build_image
    rc="$?"
    if [ "$rc" -gt 0 ]; then
        exit $rc
    fi
    test_build
    rc="$?"
    if [ "$rc" -gt 0 ]; then
        exit $rc
    fi
}
main
