name: 'GitHub-CI: Create Release'
on: workflow_dispatch
jobs:
  create-release:
    # only run the job if the trigger was from the develop branch
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0 # Required for getting commit history

      - name: Create Release
        run: |
          gh release create --generate-notes --fail-on-no-commits --draft


