name: "GitHub-CI: git head"

on:
    push: {}
    pull_request: {}

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: get HEAD commit
        id: git-head
        run: >
          echo "::set-output name=sha1::$(git rev-parse HEAD)"

      - name: Show commit hash
        run: 'echo "commit hash is ${{ steps.git-head.outputs.sha1 }}"'

      - name: Get jq version
        uses: jadutter/jq-action@${{ steps.git-head.outputs.sha1 }}
        id: version
        with:
          cmd: 'jq --version'

      - name: Show version
        run: 'echo "jq version is ${{ steps.version.outputs.stdout }}"'
